server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/db2019?useUnicode=true&characterEncoding-utf-8&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sun.springcloud.entities  # 所有Entity别名类所在包

eureka:
  client:
    service-url:
      # 单机版 defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true # 表示是否将自己注册进eurekaServer 默认为true
    fetch-registry: true # 是否从eureka server 抓取已有的注册信息，默认为tre，单店无所谓，集群必须设置为true 才能配合ribbon 使用负载均衡