server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true # 表示是否将自己注册进eurekaServer 默认为true
    fetch-registry: true # 是否从eureka server 抓取已有的注册信息，默认为tre，单店无所谓，集群必须设置为true 才能配合ribbon 使用负载均衡
spring:
  application:
    name: cloud-order-feign-server

# 设置feign 客户端超时时间
ribbon:
  # 建立连接后从服务器读取到可用资源所需要的时间
  ReadTimeout: 5000
  # 建立连接所需时间，适用于网络正常情况下，两端连接所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # fegin 日志以什么几倍监控哪个接口
    com.sun.springcloud.service.PaymentFeignService: debug